import type { Metadata } from 'next'
import './globals.css'
import NavBar from './components/NavBar/NavBar'
import Footer from './components/Footer/Footer'
import SideBar from './components/SideBar/SideBar'
import ActionButton from './components/ActionButton/ActionButton'
import ArticleContent from './components/ArticleContent/ArticleContent'



export const metadata: Metadata = {
  title: 'Assign actions to users and groups',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <NavBar />
      <ActionButton />
      <ArticleContent />
      <SideBar />
    
    
        {children}
        <Footer /> 
        </body>
    </html>
  )
}

